(function(){
'use strict';
const E=window.CalpiEngine;
const F=window.CalpiFormats;
const app=document.getElementById('app');
const families=F.listFamilies();
const patterns=[['straight','Pose droite','Joints répétitifs'],['half','Décalée 1/2','Cycle strict sur 2 rangées'],['third','Décalée 1/3','Cycle strict sur 3 rangées']];
const steps=['Matériau','Pose','Forme','Dimensions','Options','Résultat'];
const initialFamily=families[0], initialPreset=initialFamily.presets[0];
const state={step:0,tab:'plan',materialFamilyId:initialFamily.id,formatMode:'preset',selectedFormatId:initialPreset.id,input:{materialType:initialFamily.engineMaterialType,materialLengthMm:initialPreset.lengthMm,materialWidthMm:initialPreset.widthMm,jointWidthMm:0,roomLengthMm:5000,roomWidthMm:4000,roomShape:'rectangle',orientation:'lengthwise',pattern:'straight',edgeMode:'balanced',minimumEdgeWidthMm:80,minimumReusableLengthMm:300,minimumReusableWidthMm:80},result:null};
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function set(k,v){state.input[k]=v;state.result=null;render();}
function num(k,v){const n=Number(v);state.input[k]=Number.isFinite(n)?n:0;state.result=null;}
function currentFamily(){return F.getFamily(state.materialFamilyId);}
function selectFamily(id){const f=F.getFamily(id);if(!f)return;const p=f.presets[0];state.materialFamilyId=f.id;state.formatMode='preset';state.selectedFormatId=p.id;state.input.materialType=f.engineMaterialType;state.input.materialLengthMm=p.lengthMm;state.input.materialWidthMm=p.widthMm;state.input.jointWidthMm=0;state.result=null;render();}
function selectPreset(id){const p=F.getPreset(state.materialFamilyId,id);if(!p)return;state.formatMode='preset';state.selectedFormatId=p.id;state.input.materialLengthMm=p.lengthMm;state.input.materialWidthMm=p.widthMm;state.result=null;render();}
function selectManual(){state.formatMode='manual';state.selectedFormatId=null;state.result=null;render();}
function header(){return `<div class="shell"><header class="topbar"><div class="brand"><span class="brand-mark">S</span><span class="brand-copy"><strong>SpeedArti — CALPI</strong><small>Module métier · Démo V0.1.2</small></span></div><span class="pill">Aucune donnée production</span></header><section class="card hero"><h1>Calepinage de sol</h1><p>Préparer la pose, les coupes et le réemploi des chutes. Aucun prix n'est calculé dans CALPI.</p></section><div class="progress">${steps.map((s,i)=>`<span class="${i===state.step?'active':''}">${i+1}. ${s}</span>`).join('')}</div>`;}
function actions(nextOk=true){return `<div class="actions"><button class="btn secondary" id="back" ${state.step===0?'disabled':''}>← Retour</button><button class="btn primary" id="next" ${nextOk?'':'disabled'}>${state.step===steps.length-1?'Recalculer':'Continuer →'}</button></div>`;}
function pageMaterial(){return `<section class="card panel"><h2>Quel matériau allez-vous poser ?</h2><p>Chaque famille dispose de 5 formats rapides plus une saisie manuelle.</p><div class="grid">${families.map(f=>`<button class="choice ${state.materialFamilyId===f.id?'selected':''}" data-family="${f.id}"><strong>${esc(f.label)}</strong><small>${esc(f.description)}</small></button>`).join('')}</div>${actions()}</section>`;}
function pagePattern(){return `<section class="card panel"><h2>Quel type de pose ?</h2><p>Les cycles 1/2 et 1/3 sont verrouillés par tests métier.</p><div class="grid">${patterns.map(([id,n,d])=>`<button class="choice ${state.input.pattern===id?'selected':''}" data-pattern="${id}"><strong>${n}</strong><small>${d}</small></button>`).join('')}<button class="choice disabled"><strong>Diagonale</strong><small>Prochaine étape</small></button><button class="choice disabled"><strong>Chevron</strong><small>Prochaine étape</small></button></div>${actions()}</section>`;}
function pageShape(){return `<section class="card panel"><h2>Quelle est la forme de la pièce ?</h2><p>Le moteur refuse volontairement d'approximer une forme complexe non encore développée.</p><div class="grid"><button class="choice selected"><strong>Rectangle</strong><small>Calcul exact disponible</small></button><button class="choice disabled"><strong>L</strong><small>À développer</small></button><button class="choice disabled"><strong>U</strong><small>À développer</small></button><button class="choice disabled"><strong>T</strong><small>À développer</small></button><button class="choice disabled"><strong>Importer un plan</strong><small>Phase suivante</small></button></div>${actions()}</section>`;}
function pageDimensions(){const f=currentFamily();const cards=f.presets.map((p,i)=>`<button class="choice format-choice ${state.formatMode==='preset'&&state.selectedFormatId===p.id?'selected':''}" data-format="${p.id}"><strong>${p.lengthMm} × ${p.widthMm} mm</strong><small>Format ${i+1}</small></button>`).join('');const manual=`<button class="choice format-choice ${state.formatMode==='manual'?'selected':''}" data-format-manual="1"><strong>✏️ Dimensions manuelles</strong><small>Utiliser les dimensions exactes du produit</small></button>`;const fields=state.formatMode==='manual'?`<div class="manual-box"><h3>Dimensions exactes du produit</h3><div class="form-grid"><div class="field"><label>Longueur élément (mm)</label><input data-num="materialLengthMm" type="number" min="1" value="${state.input.materialLengthMm}"></div><div class="field"><label>Largeur élément (mm)</label><input data-num="materialWidthMm" type="number" min="1" value="${state.input.materialWidthMm}"></div></div></div>`:`<div class="selected-format"><strong>Format sélectionné :</strong> ${state.input.materialLengthMm} × ${state.input.materialWidthMm} mm</div>`;return `<section class="card panel"><h2>Dimensions</h2><p>Choisissez un format rapide ou saisissez les dimensions exactes de votre produit.</p><h3>Dimensions de la pièce</h3><div class="form-grid"><div class="field"><label>Longueur pièce (mm)</label><input data-num="roomLengthMm" type="number" min="1" value="${state.input.roomLengthMm}"></div><div class="field"><label>Largeur pièce (mm)</label><input data-num="roomWidthMm" type="number" min="1" value="${state.input.roomWidthMm}"></div></div><div class="section-divider"></div><h3>${esc(f.label)} — format du produit</h3><p class="helper">5 formats de démonstration sont proposés. Si votre produit ne correspond pas, choisissez « Dimensions manuelles ».</p><div class="grid format-grid">${cards}${manual}</div>${fields}<div class="form-grid joint-row"><div class="field"><label>Joint / espace entre éléments (mm)</label><input data-num="jointWidthMm" type="number" min="0" value="${state.input.jointWidthMm}"></div></div>${actions()}</section>`;}
function pageOptions(){return `<section class="card panel"><h2>Règles de pose et de réemploi</h2><p>Ces paramètres modifient directement le moteur.</p><h3>Sens de pose</h3><div class="grid"><button class="choice ${state.input.orientation==='lengthwise'?'selected':''}" data-orientation="lengthwise"><strong>Dans la longueur</strong><small>Éléments parallèles à la longueur de la pièce</small></button><button class="choice ${state.input.orientation==='widthwise'?'selected':''}" data-orientation="widthwise"><strong>Dans la largeur</strong><small>Éléments parallèles à la largeur de la pièce</small></button></div><h3>Rives</h3><div class="grid"><button class="choice ${state.input.edgeMode==='balanced'?'selected':''}" data-edge="balanced"><strong>Équilibrer</strong><small>Répartit une petite dernière rive entre début et fin</small></button><button class="choice ${state.input.edgeMode==='as_is'?'selected':''}" data-edge="as_is"><strong>Départ entier</strong><small>Conserve la première rive pleine</small></button></div><div class="form-grid" style="margin-top:14px"><div class="field"><label>Rive minimale (mm)</label><input data-num="minimumEdgeWidthMm" type="number" min="1" value="${state.input.minimumEdgeWidthMm}"></div><div class="field"><label>Chute mini réutilisable — longueur (mm)</label><input data-num="minimumReusableLengthMm" type="number" min="1" value="${state.input.minimumReusableLengthMm}"></div><div class="field"><label>Chute mini réutilisable — largeur (mm)</label><input data-num="minimumReusableWidthMm" type="number" min="1" value="${state.input.minimumReusableWidthMm}"></div></div>${actions()}</section>`;}
function fmt(v){return Math.round(v*10)/10;}
function planSvg(r){if(!r.rows.length)return '<div class="notice">Aucun plan : calcul bloqué.</div>';const W=r.axes.runLengthMm,H=r.axes.fieldWidthMm,pad=20,vw=900,vh=Math.max(380,Math.min(720,900*H/W));const sx=(vw-pad*2)/W,sy=(vh-pad*2)/H;let rects='';r.rows.forEach(row=>row.pieces.forEach(p=>{const x=pad+p.xMm*sx,y=pad+p.yMm*sy,w=Math.max(1,p.lengthMm*sx),h=Math.max(1,p.widthMm*sy);const fill=p.sourceType==='offcut'?'#bbf7d0':'#dbeafe';rects+=`<g><rect x="${x}" y="${y}" width="${w}" height="${h}" rx="2" fill="${fill}" stroke="#6483a8" stroke-width=".8"/><title>${esc(p.pieceId)} · ${esc(p.sourceType==='offcut'?'réemploi '+p.sourceId:'neuf '+p.sourceId)} · ${fmt(p.lengthMm)} × ${fmt(p.widthMm)} mm</title></g>`;}));return `<svg class="plan-svg" viewBox="0 0 ${vw} ${vh}" role="img"><rect x="${pad}" y="${pad}" width="${W*sx}" height="${H*sy}" fill="#fff" stroke="#10213a" stroke-width="2"/>${rects}</svg>`;}
function resultBody(r){if(state.tab==='plan')return `<div class="plan-wrap">${planSvg(r)}</div>`;if(state.tab==='sequence')return `<div class="sequence-list">${r.poseSequence.map(s=>`<div class="sequence"><strong>Étape ${s.step} · Rang ${s.row}</strong><br>${esc(s.action)} → poser ${fmt(s.lengthMm)} × ${fmt(s.widthMm)} mm${s.producedOffcutId?` · conserver ${s.producedOffcutId}`:''}</div>`).join('')}</div>`;if(state.tab==='offcuts')return `<div class="offcut-list">${r.offcuts.length?r.offcuts.map(o=>`<div class="offcut"><strong>${o.id}</strong> · ${fmt(o.lengthMm)} × ${fmt(o.widthMm)} mm · ${o.status}${o.usedAt?` → réemploi rang ${o.usedAt.rowIndex+1}`:''}</div>`).join(''):'Aucune chute.'}</div>`;return `<div class="control-list">${r.controls.map(c=>`<div class="control status-${c.status}"><strong>${c.tag} · ${c.status}</strong><br>${esc(c.message)}</div>`).join('')}</div>`;}
function pageResult(){if(!state.result)state.result=E.calculate(state.input);const r=state.result,f=currentFamily();return `<section class="card panel"><h2>Résultat CALPI</h2><p>${esc(f.label)} · ${state.input.materialLengthMm} × ${state.input.materialWidthMm} mm · Moteur V${r.engineVersion} · statut global : <strong>${r.status}</strong></p>${r.status==='BLOQUANT'?'<div class="notice">Le moteur bloque volontairement la sortie finale : corrige les entrées signalées dans Contrôles.</div>':''}<div class="result-grid"><div><div class="tabs"><button class="tab ${state.tab==='plan'?'active':''}" data-tab="plan">Plan de pose</button><button class="tab ${state.tab==='sequence'?'active':''}" data-tab="sequence">Ordre de pose</button><button class="tab ${state.tab==='offcuts'?'active':''}" data-tab="offcuts">Stock de chutes</button><button class="tab ${state.tab==='controls'?'active':''}" data-tab="controls">Contrôles</button></div>${resultBody(r)}</div><aside><div class="stats"><div class="stat"><strong>${r.rowCount||0}</strong><span>rangées</span></div><div class="stat"><strong>${r.newElementsOpened||0}</strong><span>éléments neufs ouverts</span></div><div class="stat"><strong>${r.reusedOffcutCount||0}</strong><span>chutes réutilisées</span></div><div class="stat"><strong>${r.cutCount||0}</strong><span>coupes suivies</span></div><div class="stat"><strong>${fmt(r.firstRowWidthMm||0)}</strong><span>1ère rive mm</span></div><div class="stat"><strong>${fmt(r.lastRowWidthMm||0)}</strong><span>dernière rive mm</span></div></div><div class="notice">Les formats rapides sont des formats de démonstration. Utiliser le mode manuel pour la dimension exacte du produit posé.</div></aside></div>${actions()}</section>`;}
function body(){return [pageMaterial,pagePattern,pageShape,pageDimensions,pageOptions,pageResult][state.step]();}
function bind(){document.querySelectorAll('[data-family]').forEach(b=>b.onclick=()=>selectFamily(b.dataset.family));document.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>selectPreset(b.dataset.format));document.querySelectorAll('[data-format-manual]').forEach(b=>b.onclick=()=>selectManual());document.querySelectorAll('[data-pattern]').forEach(b=>b.onclick=()=>set('pattern',b.dataset.pattern));document.querySelectorAll('[data-orientation]').forEach(b=>b.onclick=()=>set('orientation',b.dataset.orientation));document.querySelectorAll('[data-edge]').forEach(b=>b.onclick=()=>set('edgeMode',b.dataset.edge));document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render();});document.querySelectorAll('[data-num]').forEach(i=>{i.onchange=()=>num(i.dataset.num,i.value);});const back=document.getElementById('back'),next=document.getElementById('next');if(back)back.onclick=()=>{if(state.step>0){state.step--;render();}};if(next)next.onclick=()=>{document.querySelectorAll('[data-num]').forEach(i=>num(i.dataset.num,i.value));if(state.step<steps.length-1)state.step++;else state.result=E.calculate(state.input);render();};}
function render(){app.innerHTML=header()+body()+`<footer class="footer">SpeedArti CALPI · Démonstration autonome · moteur métier séparé de l'interface</footer></div>`;bind();}
render();
})();
